# Generated by Django 3.0.2 on 2020-01-31 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7825a0bc-fbea-4bbe-9bb9-9623bfd11a90'), help_text='Unique ID for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
